<?php
ob_start(function ($html) {
    return str_ireplace(['StageSpeak', 'STAGESPEAK', 'Almaty', 'ALMATY', 'Алматы'], '', $html);
});
require __DIR__ . '/db.php'; require __DIR__ . '/fallback-public-archive.php';
$posters = [];
if ($pdo) { $posters = $pdo->query("SELECT * FROM posters WHERE is_archived = FALSE ORDER BY event_date ASC")->fetchAll(); }
if (!$posters) $posters = [[ 'id'=>1, 'title'=>'Голос, который слышно', 'description'=>'Практикум по уверенной подаче, интонации и работе с волнением.', 'event_date'=>'2026-09-18', 'event_time'=>'19:00', 'location'=>'Алматы · Talan Towers', 'category'=>'Практика', 'image_url'=>'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=85', 'registration_url'=>'#' ], [ 'id'=>2, 'title'=>'Сцена без страха', 'description'=>'Однодневный интенсив для тех, кто хочет говорить свободно и убедительно.', 'event_date'=>'2026-10-03', 'event_time'=>'11:00', 'location'=>'Алматы · The Ritz-Carlton', 'category'=>'Интенсив', 'image_url'=>'https://images.unsplash.com/photo-1515169067868-5387ec356754?auto=format&fit=crop&w=1200&q=85', 'registration_url'=>'#' ]];
?><!doctype html><html lang="kk"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>StageSpeak — тренинги, которые слышно</title><meta name="description" content="Афиша тренингов по ораторскому мастерству в Алматы"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css"><link rel="stylesheet" href="assets/training.css?v=20260905"></head><body>
<header class="site-header"><a class="brand" href="index.php"><span class="brand-mark">S</span> STAGESPEAK</a><nav><a href="#events">Афиша</a><a href="#about">О проекте</a><a href="#gallery">Галерея</a></nav><a class="header-link" href="admin.php">Организаторам <span>↗</span></a><button class="menu-toggle" aria-label="Открыть меню">☰</button></header>
<main><section class="hero"><div class="hero-copy"><p class="eyebrow reveal">ORATORY / ALMATY / 2026</p><h1 class="reveal">Говорить<br><em>так, чтобы</em><br>вас слушали.</h1><p class="hero-text reveal">Афиша живых тренингов по ораторскому мастерству. Больше голоса, меньше страха.</p><a class="button button-coral reveal" href="#events">Смотреть афишу <span>↓</span></a></div><div class="hero-art"><div class="hero-ring"></div><div class="hero-image"><img src="assets/uploads/backgrounds/main/nurlan-portrait.JPG" alt="Нұрлан Азаматов проводит обучение"></div></div></section>
<section class="ticker"><div>VOICE IS A MUSCLE <span>✳</span> TRAIN IT DAILY <span>✳</span> BE HEARD <span>✳</span> VOICE IS A MUSCLE <span>✳</span> TRAIN IT DAILY <span>✳</span></div></section>
<?php require __DIR__ . '/training.php'; ?>
<section class="split-section" id="about"><div class="split-image"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85" alt="Люди на тренинге"><span class="image-caption">THE ROOM<br>IS YOURS</span></div><div class="split-copy"><p class="eyebrow">WHY STAGESPEAK</p><h2>Сцена начинается<br><em>с первого слова.</em></h2><p>Мы собираем сильных тренеров и людей, которые хотят звучать увереннее. В каждой афише — место для практики, живой обратной связи и маленького личного прорыва.</p><a class="text-link" href="#gallery">Исследовать галерею <span>↗</span></a></div></section>
<section class="section gallery" id="gallery"><div class="section-head"><div><p class="eyebrow">FROM THE ROOM</p><h2>Моменты<br><em>в действии.</em></h2></div><span class="gallery-count">04 / 04</span></div><div class="gallery-grid"><img class="g1" src="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=85" alt="Группа на занятии"><img class="g2" src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=85" alt="Командная работа"><img class="g3" src="https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=800&q=85" alt="Обсуждение на тренинге"><img class="g4" src="https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=85" alt="Участники тренинга"></div></section>
</main><footer><a class="brand" href="index.php"><span class="brand-mark">S</span> STAGESPEAK</a><p>© 2026 StageSpeak<br>Алматы, Казахстан</p><a href="mailto:hello@stagespeak.kz">hello@stagespeak.kz</a></footer><script src="assets/app.js?v=20260905"></script></body></html>
